apiVersion: v1
kind: PersistentVolume
metadata:
  name: weights
  labels:
    type: local
spec:
  capacity: 
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: ./weights
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads
  labels:
    type: local
spec:
  capacity: 
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ./uploads
    type: Directory