name: buildx

on:
  push:
    branches:
      - compose
      - main
    tags: 'v*'

jobs:
  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Change for main
      id: change_version
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "main" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }}; fi
    - name: Set up qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      if: github.repository == 'iqtlabs/fakefinder' && github.event_name == 'push'

    - name: Build and push platforms
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t iqtlabs/fakefinder-boken:${{ steps.change_version.outputs.VERSION }} detectors/boken && \
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t iqtlabs/fakefinder-eighteen:${{ steps.change_version.outputs.VERSION }} detectors/eighteen && \
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t iqtlabs/fakefinder-medics:${{ steps.change_version.outputs.VERSION }} detectors/medics && \
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t iqtlabs/fakefinder-ntech:${{ steps.change_version.outputs.VERSION }} detectors/ntech && \
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t iqtlabs/fakefinder-selimsef:${{ steps.change_version.outputs.VERSION }} detectors/selimsef && \
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t iqtlabs/fakefinder-wm:${{ steps.change_version.outputs.VERSION }} detectors/wm && \
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t iqtlabs/fakefinder-dash:${{ steps.change_version.outputs.VERSION }} dash && \
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t iqtlabs/fakefinder-api:${{ steps.change_version.outputs.VERSION }} api
      if: github.repository == 'iqtlabs/fakefinder' && github.event_name == 'push'
