name: test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: shell_test
      run: |
        wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" && \
        tar --xz -xvf "shellcheck-stable.linux.x86_64.tar.xz" && \
        shellcheck() { "shellcheck-stable/shellcheck" "$@"; } && \
        shellcheck --version && \
        /bin/bash --version && /bin/bash -n bin/fakefinder && shellcheck -x -e SC2016 -e SC2119 -e SC2129 -e SC2001 -e SC2038 -e SC2044 -e SC2206 bin/fakefinder
    - name: unit_test
      run: |
        export DEBIAN_FRONTEND=noninteractive && \
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        sudo apt-get update && \
        sudo apt-get install -yq --no-install-recommends python3.8 python3.8-dev && \
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 3 && \
        pip3 install -U codecov docker-compose pytest pytest-cov && \
        find . -name requirements.txt -type f -exec pip3 install -r {} \; && \
        PATH=/home/runner/.local/bin:$PATH python3 -m pytest -v -vv --cov-report term-missing --cov=. -c .coveragerc && \
        PATH=/home/runner/.local/bin:$PATH coverage report && \
        PATH=/home/runner/.local/bin:$PATH coverage xml

